{% set name = "libredwg" %}
{% set version = "0.11.3876" %}
{% set sha256 = "ba65e77adb3099bec9f8f6c2ec2c6d97457a148be0a485d7fd3c00679f332e52" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/LibreDWG/libredwg/releases/download/{{ version }}/libredwg-{{ version }}.tar.gz
    sha256: {{ sha256 }}
  - url: https://raw.githubusercontent.com/LibreDWG/libredwg/0.9.3.2543/build-aux/git-version-gen
    sha256: 129de06e36ec87882ff12a44baec1cabb1cc0fa034db4495e7d33632f4abcb01

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - swig
    - m2-autoconf  # [win]
    - m2-make  # [win]
    - m2-libtool  # [win]
    - m2-m4  # [win]
    - m2-automake-wrapper  # [win]
    - m2-texinfo  # [win]
    - posix  # [win]
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool  # [unix]
    - m4  # [unix]
    - texinfo  # [unix]
  host:
    - python
    - libxml2
    - perl
  run:
    - python
    - libxml2

test:
  imports:
    - LibreDWG  # [unix]

about:
  home: https://www.gnu.org/software/libredwg/
  doc_url: https://www.gnu.org/software/libredwg/
  dev_url: http://savannah.gnu.org/projects/libredwg/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: A free C library to handle DWG files.
  description: |
    GNU LibreDWG is a free C library to handle DWG files.
    It aims to be a free replacement for the OpenDWG libraries.
    DWG is the native file format of AutoCAD.

extra:
  recipe-maintainers:
    - looooo
